# /etc/bash/bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Enable history appending instead of overwriting.  #139609
shopt -s histappend

use_color=false

# set some environment variables
HOME=/sdcard
TERM=linux

# enable colorful terminal
if [[ ${EUID} == 0 ]] ; then
	PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W \$\[\033[00m\] '
else
	PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
fi

# Set up a ton of aliases to cover toolbox with the nice busybox
# equivalents of its commands
alias cat='busybox cat'
alias ln='busybox ln'
alias ls='busybox ls --color'
alias mount='busybox mount'
alias rm='busybox rm'
alias umount='busybox umount'
alias df='busybox df'
alias chmod='busybox chmod'
alias chown='busybox chown'
alias mv='busybox mv'
alias mkdir='busybox mkdir'
alias rmdir='busybox rmdir'
alias insmod='busybox insmod'
alias rmmod='busybox rmmod'
alias lsmod='busybox lsmod'

# Try to keep environment pollution down, EPA loves us.
unset use_color safe_term match_lhs

